# Generated by Django 3.1 on 2020-08-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_auto_20200811_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='comp.Image'),
        ),
    ]
